@host = http://localhost:9802/api/v1

# create a movie
POST {{host}}/movies HTTP/1.1
Content-Type: application/json

{
    "title": "The Godfather",
    "director": "Francis Ford Coppola",
    "year": 1972,
    "coverUrl": "https://example.com/godfather.jpg"
}